# Generated by Django 3.1.2 on 2020-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('bio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AccountImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('condition', models.TextField()),
                ('price', models.IntegerField()),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('grant_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('grant_id', models.IntegerField()),
                ('matched', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('wish_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('condition', models.TextField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
        ),
    ]
