# Generated by Django 3.1.2 on 2020-11-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='grantimage',
            name='image',
        ),
        migrations.AddField(
            model_name='accountimage',
            name='path',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grantimage',
            name='path',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
